### ISSUE TITLE
Model pack for 1.2.0

### ISSUE THREAD

**Issue by svlandeg** [AstraZeneca/KAZU#11]
Hi! 

I executed `pip install kazu` which fetched the latest `1.2.0`, but I can't find a corresponding release / model pack in https://github.com/AstraZeneca/KAZU/releases. Am I looking in the wrong spot? (I was following the readme [here](https://github.com/AstraZeneca/KAZU#getting-the-model-pack))

**Comment by EFord36** [comment]
Hi,

Thanks for letting us know!

Sorry, we mistakenly left the GitHub release in 'draft' so it wasn't visible publicly. I've made it public now - I'll close the issue but if you have further problems feel free to re-open it (or open a new one).
